version: '3'

services:
  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - ./volumes/registry:/var/lib/registry

  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: wurstmeister/kafka:0.11.0.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.34.10
      KAFKA_CREATE_TOPICS: test:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    links:
      - zookeeper

  kafka-manager:
    build: ./kafka_manager
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - 9000:9000
    links:
      - zookeeper
      - kafka

  # kafka-web-console:
  #   image: hwestphal/kafka-web-console
  #   ports:
  #     - 9000:9000
  #   links:
  #     - zookeeper
  #     - kafka
