version: '3'

services:
  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - ./.data/registry:/var/lib/registry

  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: wurstmeister/kafka:0.11.0.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 2
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    links:
      - zookeeper

  zkui:
    image: maauso/zkui
    environment:
      ZKLIST: zookeeper:2181
    ports:
      - 9090:9090
    links:
      - zookeeper

  kafka-manager:
    build: ./kafka_manager
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - 9000:9000
    links:
      - zookeeper
      - kafka

  httpbin:
    image: citizenstig/httpbin
    ports:
      - 3030:8000

  proxy:
    build: ./proxy
    environment:
      MIX_ENV: prod
      ZK_HOSTS: zookeeper:2181
      KAFKA_HOST: kafka
    ports:
      - "8000-8010:8000-8010"
    links:
      - kafka
      - zookeeper
      - httpbin

  httpd:
    image: httpd:2.2-alpine
    ports:
      - 7777:80
    volumes:
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    links:
      - httpbin
