version: '3'

services:
  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - ./.data/registry:/var/lib/registry

  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: wurstmeister/kafka:0.11.0.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.34.10
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 2
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    links:
      - zookeeper

  zkui:
    image: maauso/zkui
    environment:
      ZKLIST: zookeeper:2181
    ports:
      - 9090:9090
    links:
      - zookeeper

  kafka-manager:
    build: ./kafka_manager
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - 9000:9000
    links:
      - zookeeper
      - kafka
